tests: avoid unused import of std::borrow::Cow
The import was added since Rust 1.13 doesn't resolve Cow::Borrowed in
the tests via the the top-level import. Other versions work fine, but
in Rust 1.13 we get:

  error[E0433]: failed to resolve. Use of undeclared type or module `Cow`
     --> src/lib.rs:757:16
      |
  757 |         if let Cow::Borrowed(s) = lines[0] {
      |                ^^^^^^^^^^^^^ Use of undeclared type or module `Cow`

Since later versions do resolve Cow::Borrowed without extra imports,
they trigger a warning. Rewriting the code a bit and making the import
more local fixes it for all Rust versions.