Include benches/ again
Publishing with the benches/ directory excluded results in an error
message since the benchmark cannot be found:

  % cargo publish --dry-run
      Updating crates.io index
     Packaging textwrap v0.13.1 (/home/mg/src/textwrap)
     Verifying textwrap v0.13.1 (/home/mg/src/textwrap)
  error: failed to verify package tarball

  Caused by:
    failed to parse manifest at `/home/mg/src/textwrap/target/package/textwrap-0.13.1/Cargo.toml`

  Caused by:
    can't find `linear` bench, specify bench.path